stages:
  - ingest
  - transform

ingest:
  stage: ingest
  script:
    - pip install -r requirements.txt
    - python src/ingest.py
  artifacts:
    paths:
      - data/raw/
    expire_in: 1 week

transform:
  stage: transform
  needs: [ingest]
  script:
    - pip install -r requirements.txt
    - python src/transform.py
  artifacts:
    paths:
      - data/processed/
    expire_in: 1 week
