version: "3.9"
services:
  db:
    image: postgres:15
    container_name: rg_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: rg_user
      POSTGRES_PASSWORD: rg_pass
      POSTGRES_DB: rg_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
